# Generated by Django 5.1.7 on 2025-10-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('languages', models.CharField(help_text='Lista de lenguajes separados por coma', max_length=200)),
                ('framework', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack')], max_length=10)),
                ('github_url', models.URLField()),
            ],
        ),
    ]
