# Generated by Django 5.1.7 on 2025-10-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readme',
            field=models.TextField(blank=True, help_text='Contenido del README en formato Markdown', null=True),
        ),
    ]
