# Generated by Django 5.1.7 on 2026-03-25 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_language_remove_project_languages_project_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='framework',
        ),
    ]
