version: "3.9"

services:
  web:
    build: .
    container_name: django_base_api
    command: /entrypoint.sh
    ports:
      - "${WEB_PORT}:5012"
    volumes:
      - django_base_api:/app/media/
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal

  celery:
    build: .
    container_name: django_base_api_celery
    command: celery -A django_base_api worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal

  beat:
    build: .
    container_name: django_base_api_beat
    command: celery -A django_base_api beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: redis_django_base_api
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    # Puerto no expuesto al host; accesible solo en la red interna
    networks:
      - internal

volumes:
  django_base_api:

networks:
  internal:
    driver: bridge